name: neat_cache
version: 2.0.1
description: |
  A neat cache abstraction for wrapping in-memory or redis caches.
homepage: https://github.com/google/dart-neats/tree/master/neat_cache
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:neat_cache
dependencies:
  convert: ^3.0.0
  logging: ^1.0.1
  retry: ^3.0.0
  async: ^2.7.0
  meta: ^1.4.0
dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.4.0
environment:
  sdk: '>=2.12.0 <3.0.0'
