name: neat_cache
version: 2.0.4
description: >-
  A neat cache abstraction for wrapping in-memory or redis caches.
homepage: https://github.com/google/dart-neats/tree/master/neat_cache
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:neat_cache
topics:
 - server
 - caching
dependencies:
  convert: ^3.1.1
  logging: ^1.2.0
  retry: ^3.1.2
  async: ^2.11.0
  meta: ^1.15.0
dev_dependencies:
  test: ^1.25.5
  lints: ^4.0.0
environment:
  sdk: '^3.5.0-0'
resolution: workspace
