name: sanitize_html
version: 2.1.0
description: >-
  Function for sanitizing HTML to prevent XSS by restrict elements and
  attributes to a safe subset of allowed values.
homepage: https://github.com/google/dart-neats/tree/master/sanitize_html
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:sanitize_html
topics:
 - security
 - html
dependencies:
  html: ^0.15.4
  meta: ^1.15.0
dev_dependencies:
  test: ^1.25.5
  lints: ^4.0.0
  markdown: ^7.2.2
environment:
  sdk: '^3.5.0-0'
resolution: workspace