name: yaml_edit
version: 1.0.1
description: A library for YAML manipulation with comment and whitespace preservation.
homepage: https://github.com/google/dart-neats/tree/master/yaml_edit
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:yaml_edit
dependencies:
  meta: ^1.1.8
  yaml: ^2.2.1
  source_span: ^1.7.0
  collection: ^1.14.11
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  path: ^1.6.2
environment:
  sdk: ">=2.4.0 <3.0.0"
