name: yaml_edit
version: 1.0.3
description: A library for YAML manipulation with comment and whitespace preservation.
homepage: https://github.com/google/dart-neats/tree/master/yaml_edit
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:yaml_edit
dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  source_span: ^1.8.1
  yaml: ^3.1.0
dev_dependencies:
  path: ^1.8.0
  pedantic: ^1.11.0
  test: ^1.17.2
environment:
  sdk: ">=2.4.0 <3.0.0"
