name: http_methods
version: 1.1.1
description: >-
  List of all HTTP methods registered with IANA as list of strings, and metadata
  such as whether a method idempotent.
homepage: https://github.com/google/dart-neats/tree/master/http_methods
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:http_methods
topics:
 - http
environment:
  sdk: '^3.5.0-0'
resolution: workspace
dev_dependencies:
  test: ^1.25.5
  lints: ^4.0.0
