name: http_methods
version: 1.0.0
description: |
  List of all HTTP methods registered with IANA as list of strings, and metadata
  such as whether a method idempotent.
homepage: https://github.com/google/dart-neats/tree/master/http_methods
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:http_methods
dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.4.0
environment:
  sdk: '>=2.0.0 <3.0.0'
