name: api_analysis
description: API analysis framework
publish_to: none # DO NOT PUBLISH THIS!!!

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  async: ^2.11.0
  collection: ^1.18.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  retry: ^3.1.2
  tar: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.16.0
