name: neat_periodic_task
version: 2.0.1
description: >-
  Auxiliary classes for reliably running a periodic task in a long-running
  process such as web-server.
homepage: https://github.com/google/dart-neats/tree/master/neat_periodic_task
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:neat_periodic_task
topics:
 - server
 - periodic-tasks
dependencies:
  retry: ^3.1.2
  slugid: ^1.1.2
  json_annotation: ^4.9.0
  meta: ^1.15.0
  logging: ^1.2.0
  collection: ^1.18.0
dev_dependencies:
  test: ^1.25.5
  lints: ^4.0.0
  build_runner: ^2.4.10
  build_verify: ^3.1.0
  json_serializable: ^6.8.0
environment:
  sdk: '^3.5.0-0'
resolution: workspace