name: tar
version: 1.0.0
description: A library for reading TAR archives.
homepage: https://github.com/google/dart-neats/tree/master/tar
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:tar
dependencies:
  collection: ^1.14.13
  meta: ^1.2.2
  path: ^1.7.0
dev_dependencies:
  crypto: ^2.1.5
  pedantic: ^1.9.0
  test: ^1.14.4
environment:
  sdk: ">=2.8.1 <3.0.0"
